# NumPy Practice Exercises

### Question 1
Create a 1D NumPy array containing the numbers from 10 to 50 (inclusive) with a step of 5.

In [1]:
import numpy as np
arr1 = np.arange(10, 51, 5)
print(arr1)

[10 15 20 25 30 35 40 45 50]


### Question 2
Create a 4x6 array filled with zeros, then fill its third row (index 2) with the value 99.

In [2]:
arr2 = np.zeros((4, 6))
arr2[2, :] = 99
print(arr2)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [99. 99. 99. 99. 99. 99.]
 [ 0.  0.  0.  0.  0.  0.]]


### Question 3
Given the array: `arr = np.array([12, 45, 7, 19, 88, 3, 56, 91, 24, 67])`, print all elements that are greater than 50.

In [3]:
arr = np.array([12, 45, 7, 19, 88, 3, 56, 91, 24, 67])
print(arr[arr > 50])

[88 56 91 67]


### Question 4
Create a 5x5 identity matrix, then change its main diagonal (from top-left to bottom-right) to the values [10, 20, 30, 40, 50].

In [4]:
arr4 = np.eye(5)
np.fill_diagonal(arr4, [10, 20, 30, 40, 50])
print(arr4)

[[10.  0.  0.  0.  0.]
 [ 0. 20.  0.  0.  0.]
 [ 0.  0. 30.  0.  0.]
 [ 0.  0.  0. 40.  0.]
 [ 0.  0.  0.  0. 50.]]


### Question 5
Let `x = np.arange(1, 21).reshape(4, 5)`. Extract the following using slicing:

a. The last two rows

b. The third column

c. The 3x3 submatrix in the top-right corner

In [5]:
x = np.arange(1, 21).reshape(4, 5)
print("a. Last two rows:\n", x[-2:, :])
print("b. Third column:\n", x[:, 2])
print("c. Top-right 3x3:\n", x[:3, 2:])

a. Last two rows:
 [[11 12 13 14 15]
 [16 17 18 19 20]]
b. Third column:
 [ 3  8 13 18]
c. Top-right 3x3:
 [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


### Question 6
Given two arrays: `a = np.array([1, 2, 3, 4])` and `b = np.array([[10], [20], [30]])`.

Compute `a + b` and explain the shape.

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([[10], [20], [30]])
result = a + b
print("Resulting Array:\n", result)
print("Shape:", result.shape)

Resulting Array:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Shape: (3, 4)


### Question 7
Normalize the following array to the range [0, 1]:
`data = np.array([150, 220, 90, 300, 180, 45])`

In [7]:
data = np.array([150, 220, 90, 300, 180, 45])
normalized = (data - data.min()) / (data.max() - data.min())
print(normalized)

[0.41176471 0.68627451 0.17647059 1.         0.52941176 0.        ]


### Question 8
Standardize (z-score) the same array from question 7.

In [8]:
standardized = (data - data.mean()) / data.std()
print(standardized)

[-0.16988961  0.66956492 -0.88942206  1.62894153  0.18987662 -1.42907141]


### Question 9
Given the 2D array `mat`, compute row means, column sums, and max value position.

In [9]:
mat = np.array([[4, 8, 1, 12], [7, 3, 9, 5], [11, 2, 6, 10], [15, 0, 14, 13]])
print("Row Means:", mat.mean(axis=1))
print("Col Sums:", mat.sum(axis=0))
max_idx = np.unravel_index(mat.argmax(), mat.shape)
print(f"Max Value: {mat.max()} at {max_idx}")

Row Means: [ 6.25  6.    7.25 10.5 ]
Col Sums: [37 13 30 40]
Max Value: 15 at (np.int64(3), np.int64(0))


### Question 10
Reshape `np.arange(36)` into a 3D array of shape (3, 4, 3).

In [10]:
arr10 = np.arange(36).reshape(3, 4, 3)
print(arr10)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


### Question 11
Reverse the order of rows and columns for a 4x4 array.

In [11]:
arr11 = np.arange(1, 17).reshape(4, 4)
print(arr11[::-1, ::-1])

[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


### Question 12 & 13
Filtering names by age and replacing values.

In [12]:
ages = np.array([23, 45, 19, 34, 28, 51, 17, 39])
names = np.array(["Ali", "Sara", "Omar", "Lina", "Khaled", "Nour", "Yara", "Hassan"])
print("Names (25-40):", names[(ages >= 25) & (ages <= 40)])
ages[ages < 20] = 20
print("Updated ages:", ages)

Names (25-40): ['Lina' 'Khaled' 'Hassan']
Updated ages: [23 45 20 34 28 51 20 39]


### Question 14
6x6 random integers between 1-100 with seed 123.

In [13]:
np.random.seed(123)
print(np.random.randint(1, 101, (6, 6)))

[[ 67  93  99  18  84  58]
 [ 87  98  97  48  74  33]
 [ 47  97  26  84  79  37]
 [ 97  81  69  50  56  68]
 [  3  85  40  67  85  48]
 [ 62  49   8 100  93  53]]


### Question 15
10 random numbers from normal distribution (Mean=100, SD=15).

In [14]:
print(np.random.normal(100, 15, 10))

[127.06686834  85.51674961  80.25279948  90.61322265  95.09580659
  95.37686206 112.40676196 116.06172126  54.16633874 115.08897902]


### Question 16 & 17
Random selection and shuffling.

In [15]:
colors = np.array(["red", "blue", "green", "yellow", "purple"])
print("Random colors:", np.random.choice(colors, 3, replace=False))
nums = np.arange(1, 21)
np.random.shuffle(nums)
print("Shuffled 1-20:", nums)

Random colors: ['blue' 'yellow' 'purple']
Shuffled 1-20: [14  4  1  7 13 15 16 17  9  5  3 10 18  6 11 19  2 20 12  8]
